import "oaidl.idl";
import "ocidl.idl";

[
  uuid(2B2B8941-29D3-4F81-BB1C-381AA74C0E0D),
  version(1.0),
  helpstring("ScriptService 1.0 Type Library")
]
library ScriptServiceLib
{
  importlib("stdole2.tlb");

  [
    object,
    uuid(1CF497CD-54CE-4800-8160-3E684BBC8E55),
    oleautomation,
    nonextensible,
    helpstring("IScriptServiceScriptSource Interface"),
    pointer_default(unique)
  ]
  interface IScriptServiceScriptSource : IUnknown
  {
    HRESULT GetScriptFor([in] BSTR bsID, [out, retval] BSTR* pbsRet);
  };

  [
    object,
    uuid(8875B2E2-0AB1-4BF0-A82A-8538DBB5535B),
    oleautomation,
    nonextensible,
    helpstring("IScriptServiceInstance Interface"),
    pointer_default(unique)
  ]
  interface IScriptServiceInstance : IUnknown
  {
    [id(1), helpstring(
      "Initializes the instance. Can return S_FALSE if the internal hidden browser document is not ready yet."
      "If it returns S_FALSE then the instance is not initialized and at least one another call to Init must be done later.")]
    HRESULT Init([in, string] const OLECHAR* extensionId, [in, string] const OLECHAR* resourcesDir);

    [id(2), helpstring("Returns IMagpieApplication so the script engine can be initialized.")]
    HRESULT GetApplication([out, retval] LPUNKNOWN /* IMagpieApplication */ *pApplication);

    [id(3), helpstring("Registers a new client tab id. Called from BHO before content scripts for particular tab are loaded.")]
    HRESULT RegisterTab([out, retval] INT *tabId);

    [id(4), helpstring("Retrieves ISalsitaApiService implementation from the service.")]
    HRESULT GetSalsitaApiService([out, retval] LPUNKNOWN /* ISalsitaApiService */ *pService);
  };

  [
    uuid(8E0DF3C3-BA52-47F7-B601-307E5CB207EF),
    helpstring("ScriptServiceInstance Class")
  ]
  coclass ScriptServiceInstance
  {
    [default] interface IScriptServiceInstance;
  };

  [
    object,
    uuid(E569F09A-55AA-49B9-90EA-BE0B6AA487E1),
    oleautomation,
    nonextensible,
    helpstring("Client interface to script service client"),
    pointer_default(unique)
  ]
  interface IScriptServiceInstanceClient : IUnknown
  {
    [id(1)]
    HRESULT RegisterTab([out, retval] INT *tabId);

    [id(2)]
    HRESULT GetSalsitaApiService([out, retval] LPUNKNOWN /* ISalsitaApiService */ *pService);
  };

  [
    object,
    uuid(954448CA-1894-4743-9261-BBE3C932FA27),
    oleautomation,
    nonextensible,
    helpstring("IScriptServiceFactory Interface"),
    pointer_default(unique)
  ]
  interface IScriptServiceFactory : IUnknown
  {
    HRESULT GetScriptServiceInstance([out, retval] LPUNKNOWN* /* IScriptServiceInstanceClient */ ppUnk);
  };
};
