#pragma once

namespace LIB_COMHelper {

/**
 * Handles pushing manifest into the activation stack.
 * http://msdn.microsoft.com/en-us/library/windows/desktop/aa374166%28v=vs.85%29.aspx
 * This enables loading of com libraries without the need for registration.
 */
class CActivationHelper
{
private:
  WCHAR path[MAX_PATH], dir[MAX_PATH];
  DWORD error;
  HANDLE contextHandle;
  ULONG_PTR cookie;
public:
  /**
   * Creates activation context from RT_MANIFEST #2 contained in calling dll.
   */
  CActivationHelper(HMODULE callerModule);
  ~CActivationHelper();
  inline DWORD GetErrorCode() { return error; }

private:
  // prevent copying the object which would improperly duplicate the handle which then woul get destroyed while still being used
  // body is generated by compiler
  CActivationHelper(const CActivationHelper&);
  CActivationHelper& operator=(const CActivationHelper&);
};

} // namespace LIB_COMHelper